sudo: false

language: php

php:
  - 7.1

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install

script:
  - mkdir -p build/logs
  - php bin/phpunit -c phpunit-metrics-without-infrastructure.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - php bin/coveralls -v -c .coveralls.yml
