#!/usr/bin/env php
<?php

require __DIR__.'/../vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('Tic Tac Toe', '1.0.0');
$application->add(new \App\Command\StartGameCommand());
$application->add(new \App\Command\CreateUserCommand());
$application->run();
